# Generated by Django 2.2.17 on 2021-01-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='waktu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('identitas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perpustakaan.Identitas')),
                ('status_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.status')),
            ],
            bases=('perpustakaan.identitas',),
        ),
        migrations.CreateModel(
            name='penerbit',
            fields=[
                ('identitas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perpustakaan.Identitas')),
            ],
            bases=('perpustakaan.identitas',),
        ),
        migrations.CreateModel(
            name='pengarang',
            fields=[
                ('identitas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perpustakaan.Identitas')),
            ],
            bases=('perpustakaan.identitas',),
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('Tahun', models.DateField()),
                ('ISBN', models.IntegerField(null=True)),
                ('kategori_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.Kategori')),
                ('penerbit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.penerbit')),
                ('pengarang_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.pengarang')),
            ],
        ),
        migrations.CreateModel(
            name='peminjaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlahpinjaman', models.IntegerField(null=True)),
                ('buku_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.Buku')),
                ('waktu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.waktu')),
                ('anggota_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.Anggota')),
            ],
        ),
    ]
