# Generated by Django 3.1.4 on 2021-01-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_auto_20210121_0231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='waktu',
        ),
    ]
